image: alpine:latest

stages:
  - test
  - build
  - release

test:
  image: python:2.7-alpine
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - flake8
    - ./scripts/xgettext.sh

build:
  stage: build
  before_script:
    - apk update
    - apk add git make zip
  script:
    - make
  only:
    - master

release:
  stage: release
  before_script:
    - apk update
    - apk add git make lftp zip
  script:
    - make
  after_script:
    - |
        lftp -c "open 'ftp://$FTP_USER:$FTP_PASS@$FTP_HOST'; \
        cd script.quasar.burst; \
        mirror --reverse --verbose --exclude '.*' --exclude '.*/' --include-glob addon.xml; \
        mirror --reverse --verbose --exclude '.*' --exclude '.*/' --include-glob *.zip; \
        exit;"
  artifacts:
    paths:
    - script.quasar.burst-${CI_BUILD_TAG:1}.zip
  only:
    - tags
